version: "3.9"
   
services:
  sfn:
    image: mtik00/steam-free-notifier:latest
    environment:
      - SFN_APP_CACHE_PATH=/tmp/app_cache/app_cache.json
      - SFN_APP_SETTINGS_PATH=/tmp/app_config/settings.yml
      - SFN_APP_DEBUG=1
    command:
      - python
      - app.py
      - --debug
    volumes:
      - ${PWD}:/tmp/app_config:ro
      - ${PWD}/app_cache:/tmp/app_cache
