version: "3.9"

services:
  sfn:
    image: mtik00/free-game-notifier:latest
    environment:
      - SFN_APP_CACHE_PATH=/tmp/app_cache/app_cache.json
      - SFN_APP_CONFIG_PATH=/tmp/app_config/settings.yml
      - SFN_APP_DEBUG=1
    command:
      - python
      - app.py
      - --debug
      # --dry-run
    volumes:
      - ${PWD}:/tmp/app_config:ro
      - ${PWD}/app_cache:/tmp/app_cache
