---
# Use the "TZ Database name" from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Denver 
cache_path: /tmp/app_cache/app_cache.json

feeds:
  steam:
    # This shows how to use a local file for the RSS feed instead of the "live"
    # feed.  This is helpful for testing, and should be changed once everything
    # is working.  You'll first need to download the file with:
    #   curl -o feed.xml https://steamcommunity.com/groups/freegamesfinders/rss/
    # This section is a list of url-like items.  Each steam feed will be processed.
    - /tmp/app_config/feed.xml
    # - https://steamcommunity.com/groups/freegamesfinders/rss/

notifiers:
  slack:
    # This is a list of the URLs for your Slack webhooks.  If empty, the message
    # will be sent to stdout (you should use `debug: true` when doing so).
    # This is a list of url-like items.
    - null

debug: true

# Each key in this section will be tested against the URL containing the redemption
# URL.  The first one found will be used for the notification message.
icons:
    steam: https://store.steampowered.com/favicon.ico
    epic: https://www.epicgames.com/favicon.ico
    humble: https://humblebundle-a.akamaihd.net/static/hashed/47e474eed38083df699b7dfd8d29d575e3398f1e.ico