repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-yaml
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black
