name: build the image

on:
  push:
    branches: master
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build the image
        run: |
          docker buildx build --push \
            --tag mtik00/steam-free-notifier:latest \
            --platform linux/amd64,linux/arm64 -f docker/Dockerfile .
